version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/app/dashboard/" 
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "daily"
